version: '3.9'
services:
  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=passme
      - DB_VENDOR=h2
    ports:
      - '8180:8080'
    image: 'quay.io/keycloak/keycloak:15.0.2'
    networks:
      - keycloak

networks:
  keycloak:
    name: keycloak_network
    driver: bridge